name: question_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.2.0
  equatable: ^2.0.5
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  html_unescape: ^2.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pictures/
