// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnICNg4HJPjqE4ZQSizo4LxGKDPKnuXSI',
    appId: '1:259198524234:web:833760249083b2bf4dffb3',
    messagingSenderId: '259198524234',
    projectId: 'question-app-af3e4',
    authDomain: 'question-app-af3e4.firebaseapp.com',
    storageBucket: 'question-app-af3e4.appspot.com',
    measurementId: 'G-ZXHZJF996W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwZcK4gU3VfUG9xEaWwn-7MpJ74iWnXs',
    appId: '1:259198524234:android:a8f4791e1c31bebd4dffb3',
    messagingSenderId: '259198524234',
    projectId: 'question-app-af3e4',
    storageBucket: 'question-app-af3e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cE0c1oeMZp7XU7-ImXo4xRzliytzBrk',
    appId: '1:259198524234:ios:af57d622a05abe4d4dffb3',
    messagingSenderId: '259198524234',
    projectId: 'question-app-af3e4',
    storageBucket: 'question-app-af3e4.appspot.com',
    iosBundleId: 'com.example.questionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2cE0c1oeMZp7XU7-ImXo4xRzliytzBrk',
    appId: '1:259198524234:ios:af57d622a05abe4d4dffb3',
    messagingSenderId: '259198524234',
    projectId: 'question-app-af3e4',
    storageBucket: 'question-app-af3e4.appspot.com',
    iosBundleId: 'com.example.questionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnICNg4HJPjqE4ZQSizo4LxGKDPKnuXSI',
    appId: '1:259198524234:web:5bab983d2e3323a94dffb3',
    messagingSenderId: '259198524234',
    projectId: 'question-app-af3e4',
    authDomain: 'question-app-af3e4.firebaseapp.com',
    storageBucket: 'question-app-af3e4.appspot.com',
    measurementId: 'G-9C7L6CDXYZ',
  );
}
